name: FTP Deploy

on:
  push:
    branches:
      - main

jobs:
  ftp-deploy:
    name: Upload modified files via FTP
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get previous commit SHA
        id: prev-commit
        run: |
          git fetch origin main
          echo "PREV_COMMIT=$(git rev-parse HEAD^1 || echo 'initial')" >> $GITHUB_ENV

      - name: Get changed files
        id: changes
        run: |
          if [ "$PREV_COMMIT" != "initial" ]; then
            git diff --name-only $PREV_COMMIT HEAD > changed_files.txt
          else
            git ls-files > changed_files.txt
          fi
          echo "CHANGED_FILES=$(cat changed_files.txt | tr '\n' ' ')" >> $GITHUB_ENV

      - name: Upload files via FTP
        uses: sebastianpopp/ftp-action@v1.1.0
        with:
          host: ${{ secrets.FTP_HOST }}
          user: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          localDir: .
          remoteDir: /public_html/
          include: ${{ env.CHANGED_FILES }}
