name: FTP Deploy

on:
  push:
    branches:
      - main

jobs:
  ftp-deploy:
    name: Upload modified files via FTP
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Determine previous commit
        id: prev-commit
        run: |
          if git rev-parse HEAD^1 > /dev/null 2>&1; then
            PREV_COMMIT=$(git rev-parse HEAD^1)
          else
            PREV_COMMIT=""
          fi
          echo "PREV_COMMIT=$PREV_COMMIT" >> $GITHUB_ENV

      - name: Get changed files
        id: changes
        run: |
          if [ -n "$PREV_COMMIT" ]; then
            git diff --name-only $PREV_COMMIT HEAD > changed_files.txt
          else
            git ls-files > changed_files.txt
          fi
          echo "CHANGED_FILES=$(cat changed_files.txt | tr '\n' ' ')" >> $GITHUB_ENV

      - name: Upload files via FTP
        uses: sebastianpopp/ftp-action@v1.1.0
        with:
          host: ${{ secrets.FTP_HOST }}
          user: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          localDir: .
          remoteDir: /public_html/
          include: ${{ env.CHANGED_FILES }}
